version: 2
updates:
    # Enable version updates for Python
    - package-ecosystem: "pip"
      directory: "/"
      # Check for updates once a week
      schedule:
          interval: "weekly"
    - package-ecosystem: "github-actions"
      directory: "/"
      # Check for updates once a week
      schedule:
          interval: "weekly"
