name: Linters (flake8, black, isort)

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-python@v4.7.0
      - uses: pre-commit/action@v3.0.0
